# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(help_text='Enter a mobile manufacturer (e.g. Samsung, HTC).', max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('review', models.TextField(help_text='Enter a review for the mobile', max_length=1000)),
                ('operating_system', models.CharField(max_length=200, null=True)),
                ('screen_technology', models.CharField(max_length=200, null=True)),
                ('screen_size', models.FloatField()),
                ('price', models.CharField(max_length=200, null=True)),
                ('repository', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('u', 'Unavailable'), ('o', 'Outdated')], default='a', help_text='Mobile availability', max_length=1)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, null=True)),
                ('product', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=2000, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
